### ISSUE TITLE
Multiple issues with the Ingestion phase

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#13]
An exception of type `InvalidOperationException (value cannot be null)` is thrown in `SW.FluentOlap.Ingester.SqlTranslator` method `SqlMapsFromTypeMaps` due to the `InternalType` property being null for many properties and entries inside the type map.
1. One instance is properties with double or long types because they are not taken into account in `TypeUtils.TryGuessInternalType`.
2. Another instance is properties that've been added via the new `Property(string, AnalyticalObject<TProperty>)` method. The reason behind this behaviour is that in `PopulateServiceMaps` the condition `TypeMap.ContainsKey(key)` will evaluate to false and hence the added property which doesn't have internal type because it represents a complex type will be added to the root-object type map dictionary.

![image](https://user-images.githubusercontent.com/65822550/101400706-92f85280-38d1-11eb-80ba-7b370f51c0b2.png)

Trying to run the solution to the end by ignoring the offending properties resulted in another exception:
`MySql.Data.MySqlClient.MySqlException: Identifier name 'corporatecustomerid_corporatecustomerdto_licenseregistrationnumber' is too long.`

**Comment by shaheensarafa** [comment]
The first 2 issues have been fixed locally.

As for the name being long issue, an overhaul of the naming process is currently in progress.

**Comment by shaheensarafa** [comment]
Please pull the branch shaheen/minimumViableKey and experiment with it. 

If you like the new naming strategy, we can work on refining it and adding it to master. This branch currently passes the Definition & Collection UTs

**Comment by mahmoud-syr** [comment]
Dear Shaheen, I tried to use the code in the branch `branch shaheen/minimumViableKey` but I'm still having issues:
1. I had to fix the internal type for long and double myself, I think you didn't get the latest version of master before branching into `branch shaheen/minimumViableKey`
2. I have got an exception `key doesn't exist in the dictionary (NEVER)` I tracked the issue down until I found it in an if condition in `SqlTypeTranslator` class, please take a look at the image below:
![image](https://user-images.githubusercontent.com/65822550/102116112-c50f3480-3e3c-11eb-9d56-bd031f1cd2be.png)
I fixed it by comparing directly between `typeString` property.
3. After that I received another `NullReferenceException` in `MariaDbProvider` line number `141` :`tmpValues.Add($"'{value.ToString()}'");`. I removed the unnecessary `.ToString`
4. Finally, I received the following Sql Exception:
![image](https://user-images.githubusercontent.com/65822550/102117226-5c28bc00-3e3e-11eb-83a6-58da91aa3acd.png)

My guess in regards to `4` is that the individual customer value was null, I think the Populationresult need to maintain the equivalent sql type or there should be a way to check that column's sql type in case it's nullable, `DBNull.Value` or `null` should be used instead.

**Comment by shaheensarafa** [comment]
Hello, you were right about not pulling latest master; my bad.

I fixed that and addressed the other issues in the latest push to my branch.

In a wide table, usually all values are nullable by default and that is what FluentOlap will work with for now, until further notice.

Please do pull the latest branch along with the updated unit test and let me know how it goes.

**Comment by mahmoud-syr** [comment]
Dear Shaheen thanks for your help so far but I'm still having issues.
First, I had to change the statement from `tmpValues.Add($"'{value?? "NULL"}'");` to `tmpValues.Add(value != null ? $"'{value}'" : "NULL");` because the former will be treated as an ordinary string value the latter on the other hand will be treated as null. Now, I'm receiving the following exception:

> MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime value: '10/5/2020 10:53:30 AM' for column `fluentolap`.`shipmentlivecapacitydto`.`shipmentlivecapacitydto_airwaybilldate` at row 1

I tried to find a way to sort of "normalize" the datetime values sent by the ingester but couldn't find a way to do that without a major refactoring/deep-look, so I'll be waiting for your response.

Thanks again.

**Comment by shaheensarafa** [comment]
This issue has gotten very bloated and is covering way too many things. I'm closing this and opening new issues.

Regardless, I will look into a UT overhaul and I have a feature set in mind that might solve the issue with the datetime and others.
